services:
  # Backend API service
  - type: web
    name: expense-analytics-backend-high-point
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/test

  # Frontend static site
  - type: static
    name: expense-analytics-frontend-high-point
    plan: free
    staticPublishPath: ./
